/**:
  ros__parameters:
    module_list:
      - "blind_spot"
      - "crosswalk"
      - "detection_area"
      - "intersection"
      - "no_stopping_area"
      - "traffic_light"
      - "intersection_occlusion"

    default_enable_list:
      - "blind_spot"
      - "crosswalk"
      - "detection_area"
      - "intersection"
      - "no_stopping_area"
      - "traffic_light"
      - "intersection_occlusion"
