version: 1.0

stylesheets:
  - { path: package://multi_data_monitor/tutorials/04/style4.css }

widgets:
  root:
    class: multi_data_monitor::Matrix
    children:
      - class: multi_data_monitor::Title
        title: ControlMode
        input:
          model: filter
          input:
            {
              model: topic,
              name: /vehicle/status/control_mode,
              data: mode,
              type: autoware_auto_vehicle_msgs/msg/ControlModeReport,
            }
          rules:
            - class: multi_data_monitor::Switch
              default: { value: UNKNOWN, attrs: { test: "" } }
              mapping:
                0: { value: NO_COMMAND, attrs: { test: "" } }
                1: { value: AUTO, attrs: { test: "" } }
                2: { value: MANUAL, attrs: { test: one } }
                3: { value: DISENGAGED, attrs: { test: "" } }
                4: { value: NOT_READY, attrs: { test: "" } }
      - class: multi_data_monitor::Title
        title: OperationMode
        input:
          model: filter
          input:
            {
              model: topic,
              name: /control/operation_mode,
              data: mode,
              type: tier4_system_msgs/msg/OperationMode,
            }
          rules:
            - class: multi_data_monitor::Switch
              default: { value: UNKNOWN, attrs: { test: "" } }
              mapping:
                0: { value: STOP, attrs: { test: "" } }
                1: { value: MANUAL, attrs: { test: one } }
                2: { value: REMOTE_OPERATOR, attrs: { test: "" } }
                3: { value: LOCAL_OPERATOR, attrs: { test: "" } }
                4: { value: TRANSITION, attrs: { test: "" } }
                5: { value: AUTO, attrs: { test: "" } }
